"""Cellular Transformer research prototypes."""

from .benchmarks import MemoryTaskResult, run_memory_task, sweep_memory_tasks
from .candidate_cache import (
    CandidateCacheConfig,
    CandidateCacheTrialResult,
    CandidateCacheUpdate,
    LowBitCandidateCache,
    run_candidate_cache_trial,
)
from .candidate_indexer import (
    CandidateIndexerTrialResult,
    CandidateTensorDiagnosticResult,
    LowBitAdditiveCandidateIndexer,
    LowBitLinearCandidateIndexer,
    run_candidate_indexer_trial,
    run_candidate_tensor_diagnostic,
    train_additive_candidate_indexer,
    train_linear_candidate_indexer,
)
from .candidate_scorer import (
    CandidateScorerTrialResult,
    LowBitCandidateScorerLUT,
    run_candidate_scorer_trial,
    train_future_window_candidate_scorer_lut,
    train_repeat_candidate_scorer_lut,
)
from .cellular_moe import CellularMoE, CellularMoEConfig, MoERolloutResult, MoEStepStats
from .chip_model import ChipConfig, ChipProfile, TileConfig, profile_chip
from .compressed_block_indexer import (
    CompressedBlockBudgetPoint,
    CompressedBlockBudgetSweepResult,
    CompressedBlockIndexConfig,
    CompressedBlockIndexResult,
    CsaHcaPolicyPoint,
    CsaHcaPolicyResult,
    HcaSummaryQualityPoint,
    HcaSummaryQualityResult,
    LowBitCompressedBlockIndex,
    run_csa_hca_policy_trial,
    run_compressed_block_budget_sweep,
    run_compressed_block_index_trial,
    run_hca_summary_quality_sweep,
)
from .dense_context import (
    DenseContextConfig,
    DenseContextResult,
    LowBitDenseContext,
    run_dense_context_trial,
)
from .efficiency import EfficiencyComparison, HarcEventEfficiency, compare_to_transformer_kv
from .admission_policy import (
    LearnedAdmissionResult,
    LowBitAdmissionLUT,
    future_repeat_labels,
    run_learned_admission_trial,
    train_repeat_admission_lut,
)
from .output_head import (
    OutputHeadComparison,
    OutputHeadConfig,
    OutputHeadMetrics,
    compare_output_heads,
    estimate_output_head,
)
from .propagation import (
    PropagationResult,
    harc_ca_edges,
    line_edges,
    propagation_distances,
    shortest_propagation_steps,
)
from .retrieval import (
    HashRouteCAM,
    HashRouteCAMConfig,
    InsertResult,
    LookupResult,
    RecallTrialResult,
    TieredHashRouteCAM,
    TieredHashRouteCAMConfig,
    TieredLookupResult,
    run_recall_trial,
)
from .synthetic_lm import DualPathSyntheticLM, SyntheticLMConfig, SyntheticLMResult, run_synthetic_lm_trial

__all__ = [
    "CellularMoE",
    "CellularMoEConfig",
    "CandidateCacheConfig",
    "CandidateIndexerTrialResult",
    "CandidateTensorDiagnosticResult",
    "CandidateCacheTrialResult",
    "CandidateCacheUpdate",
    "CandidateScorerTrialResult",
    "ChipConfig",
    "ChipProfile",
    "CompressedBlockBudgetPoint",
    "CompressedBlockBudgetSweepResult",
    "CompressedBlockIndexConfig",
    "CompressedBlockIndexResult",
    "CsaHcaPolicyPoint",
    "CsaHcaPolicyResult",
    "HcaSummaryQualityPoint",
    "HcaSummaryQualityResult",
    "DualPathSyntheticLM",
    "HashRouteCAM",
    "HashRouteCAMConfig",
    "DenseContextConfig",
    "DenseContextResult",
    "EfficiencyComparison",
    "InsertResult",
    "HarcEventEfficiency",
    "LearnedAdmissionResult",
    "LookupResult",
    "LowBitAdmissionLUT",
    "LowBitAdditiveCandidateIndexer",
    "LowBitLinearCandidateIndexer",
    "LowBitCompressedBlockIndex",
    "LowBitCandidateScorerLUT",
    "LowBitDenseContext",
    "LowBitCandidateCache",
    "MoERolloutResult",
    "MoEStepStats",
    "MemoryTaskResult",
    "OutputHeadComparison",
    "OutputHeadConfig",
    "OutputHeadMetrics",
    "PropagationResult",
    "RecallTrialResult",
    "SyntheticLMConfig",
    "SyntheticLMResult",
    "TieredHashRouteCAM",
    "TieredHashRouteCAMConfig",
    "TieredLookupResult",
    "TileConfig",
    "harc_ca_edges",
    "line_edges",
    "profile_chip",
    "propagation_distances",
    "compare_to_transformer_kv",
    "compare_output_heads",
    "estimate_output_head",
    "future_repeat_labels",
    "run_dense_context_trial",
    "run_candidate_cache_trial",
    "run_candidate_indexer_trial",
    "run_candidate_tensor_diagnostic",
    "run_candidate_scorer_trial",
    "run_compressed_block_budget_sweep",
    "run_compressed_block_index_trial",
    "run_csa_hca_policy_trial",
    "run_hca_summary_quality_sweep",
    "run_learned_admission_trial",
    "run_memory_task",
    "run_recall_trial",
    "run_synthetic_lm_trial",
    "shortest_propagation_steps",
    "sweep_memory_tasks",
    "train_repeat_admission_lut",
    "train_future_window_candidate_scorer_lut",
    "train_additive_candidate_indexer",
    "train_linear_candidate_indexer",
    "train_repeat_candidate_scorer_lut",
]
